// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Action_Type int32

const (
	Action_MOVE        Action_Type = 0
	Action_ATTACK      Action_Type = 1
	Action_RECEIVE_HIT Action_Type = 2
)

var Action_Type_name = map[int32]string{
	0: "MOVE",
	1: "ATTACK",
	2: "RECEIVE_HIT",
}

var Action_Type_value = map[string]int32{
	"MOVE":        0,
	"ATTACK":      1,
	"RECEIVE_HIT": 2,
}

func (x Action_Type) String() string {
	return proto.EnumName(Action_Type_name, int32(x))
}

func (Action_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{0, 0}
}

type JoinResponse_Type int32

const (
	JoinResponse_ACCEPT JoinResponse_Type = 0
	JoinResponse_REJECT JoinResponse_Type = 1
)

var JoinResponse_Type_name = map[int32]string{
	0: "ACCEPT",
	1: "REJECT",
}

var JoinResponse_Type_value = map[string]int32{
	"ACCEPT": 0,
	"REJECT": 1,
}

func (x JoinResponse_Type) String() string {
	return proto.EnumName(JoinResponse_Type_name, int32(x))
}

func (JoinResponse_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{2, 0}
}

type Player_Type int32

const (
	Player_ACTIVE    Player_Type = 0
	Player_SPECTATOR Player_Type = 1
)

var Player_Type_name = map[int32]string{
	0: "ACTIVE",
	1: "SPECTATOR",
}

var Player_Type_value = map[string]int32{
	"ACTIVE":    0,
	"SPECTATOR": 1,
}

func (x Player_Type) String() string {
	return proto.EnumName(Player_Type_name, int32(x))
}

func (Player_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{3, 0}
}

type Action struct {
	Type                 Action_Type `protobuf:"varint,1,opt,name=type,proto3,enum=pb.Action_Type" json:"type,omitempty"`
	Damage               int64       `protobuf:"varint,2,opt,name=damage,proto3" json:"damage,omitempty"`
	Identity             []byte      `protobuf:"bytes,3,opt,name=identity,proto3" json:"identity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{0}
}

func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (m *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(m, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

func (m *Action) GetType() Action_Type {
	if m != nil {
		return m.Type
	}
	return Action_MOVE
}

func (m *Action) GetDamage() int64 {
	if m != nil {
		return m.Damage
	}
	return 0
}

func (m *Action) GetIdentity() []byte {
	if m != nil {
		return m.Identity
	}
	return nil
}

type JoinRequest struct {
	Identity             []byte   `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRequest) Reset()         { *m = JoinRequest{} }
func (m *JoinRequest) String() string { return proto.CompactTextString(m) }
func (*JoinRequest) ProtoMessage()    {}
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{1}
}

func (m *JoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRequest.Unmarshal(m, b)
}
func (m *JoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRequest.Marshal(b, m, deterministic)
}
func (m *JoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRequest.Merge(m, src)
}
func (m *JoinRequest) XXX_Size() int {
	return xxx_messageInfo_JoinRequest.Size(m)
}
func (m *JoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRequest proto.InternalMessageInfo

func (m *JoinRequest) GetIdentity() []byte {
	if m != nil {
		return m.Identity
	}
	return nil
}

type JoinResponse struct {
	Type                 JoinResponse_Type `protobuf:"varint,1,opt,name=type,proto3,enum=pb.JoinResponse_Type" json:"type,omitempty"`
	Authorization        []byte            `protobuf:"bytes,2,opt,name=authorization,proto3" json:"authorization,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *JoinResponse) Reset()         { *m = JoinResponse{} }
func (m *JoinResponse) String() string { return proto.CompactTextString(m) }
func (*JoinResponse) ProtoMessage()    {}
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{2}
}

func (m *JoinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinResponse.Unmarshal(m, b)
}
func (m *JoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinResponse.Marshal(b, m, deterministic)
}
func (m *JoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinResponse.Merge(m, src)
}
func (m *JoinResponse) XXX_Size() int {
	return xxx_messageInfo_JoinResponse.Size(m)
}
func (m *JoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinResponse proto.InternalMessageInfo

func (m *JoinResponse) GetType() JoinResponse_Type {
	if m != nil {
		return m.Type
	}
	return JoinResponse_ACCEPT
}

func (m *JoinResponse) GetAuthorization() []byte {
	if m != nil {
		return m.Authorization
	}
	return nil
}

type Player struct {
	Identity             []byte      `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	X                    int64       `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int64       `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	Health               int64       `protobuf:"varint,4,opt,name=health,proto3" json:"health,omitempty"`
	Experience           int64       `protobuf:"varint,5,opt,name=experience,proto3" json:"experience,omitempty"`
	Type                 Player_Type `protobuf:"varint,6,opt,name=type,proto3,enum=pb.Player_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{3}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetIdentity() []byte {
	if m != nil {
		return m.Identity
	}
	return nil
}

func (m *Player) GetX() int64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Player) GetY() int64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Player) GetHealth() int64 {
	if m != nil {
		return m.Health
	}
	return 0
}

func (m *Player) GetExperience() int64 {
	if m != nil {
		return m.Experience
	}
	return 0
}

func (m *Player) GetType() Player_Type {
	if m != nil {
		return m.Type
	}
	return Player_ACTIVE
}

type StatusUpdateRequest struct {
	Player               *Player  `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	Action               *Action  `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusUpdateRequest) Reset()         { *m = StatusUpdateRequest{} }
func (m *StatusUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*StatusUpdateRequest) ProtoMessage()    {}
func (*StatusUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{4}
}

func (m *StatusUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusUpdateRequest.Unmarshal(m, b)
}
func (m *StatusUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusUpdateRequest.Marshal(b, m, deterministic)
}
func (m *StatusUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusUpdateRequest.Merge(m, src)
}
func (m *StatusUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_StatusUpdateRequest.Size(m)
}
func (m *StatusUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatusUpdateRequest proto.InternalMessageInfo

func (m *StatusUpdateRequest) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

func (m *StatusUpdateRequest) GetAction() *Action {
	if m != nil {
		return m.Action
	}
	return nil
}

type StatusUpdateResponse struct {
	Player               *Player  `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusUpdateResponse) Reset()         { *m = StatusUpdateResponse{} }
func (m *StatusUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*StatusUpdateResponse) ProtoMessage()    {}
func (*StatusUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{5}
}

func (m *StatusUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusUpdateResponse.Unmarshal(m, b)
}
func (m *StatusUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusUpdateResponse.Marshal(b, m, deterministic)
}
func (m *StatusUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusUpdateResponse.Merge(m, src)
}
func (m *StatusUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_StatusUpdateResponse.Size(m)
}
func (m *StatusUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusUpdateResponse proto.InternalMessageInfo

func (m *StatusUpdateResponse) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

func init() {
	proto.RegisterEnum("pb.Action_Type", Action_Type_name, Action_Type_value)
	proto.RegisterEnum("pb.JoinResponse_Type", JoinResponse_Type_name, JoinResponse_Type_value)
	proto.RegisterEnum("pb.Player_Type", Player_Type_name, Player_Type_value)
	proto.RegisterType((*Action)(nil), "pb.Action")
	proto.RegisterType((*JoinRequest)(nil), "pb.JoinRequest")
	proto.RegisterType((*JoinResponse)(nil), "pb.JoinResponse")
	proto.RegisterType((*Player)(nil), "pb.Player")
	proto.RegisterType((*StatusUpdateRequest)(nil), "pb.StatusUpdateRequest")
	proto.RegisterType((*StatusUpdateResponse)(nil), "pb.StatusUpdateResponse")
}

func init() { proto.RegisterFile("game.proto", fileDescriptor_38fc58335341d769) }

var fileDescriptor_38fc58335341d769 = []byte{
	// 449 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0xad, 0xdb, 0x10, 0x8d, 0xdb, 0x8e, 0x46, 0xe6, 0x2b, 0xda, 0xc3, 0x54, 0x0c, 0x0f, 0xdd,
	0xc3, 0xaa, 0xa9, 0xbc, 0xf1, 0x56, 0x22, 0x0b, 0x3a, 0x84, 0x56, 0x79, 0x66, 0x0f, 0x48, 0x08,
	0xb9, 0xed, 0xd5, 0x1a, 0x69, 0x4d, 0x4c, 0xe2, 0x4a, 0x0d, 0x42, 0xe2, 0x2f, 0xf0, 0x93, 0xf8,
	0x69, 0xc8, 0x71, 0x68, 0x93, 0x82, 0x10, 0x8f, 0xd7, 0xe7, 0xe6, 0xf8, 0x9c, 0xe3, 0x13, 0x80,
	0x5b, 0xb5, 0xc6, 0x91, 0xce, 0x52, 0x93, 0xd2, 0xb6, 0x9e, 0xb3, 0x1f, 0x04, 0xfc, 0xc9, 0xc2,
	0xc4, 0x69, 0x42, 0x9f, 0x83, 0x67, 0x0a, 0x8d, 0x21, 0x19, 0x90, 0xe1, 0x83, 0x71, 0x7f, 0xa4,
	0xe7, 0x23, 0x87, 0x8c, 0x64, 0xa1, 0x51, 0x94, 0x20, 0x7d, 0x02, 0xfe, 0x52, 0xad, 0xd5, 0x2d,
	0x86, 0xed, 0x01, 0x19, 0x76, 0x44, 0x35, 0xd1, 0x13, 0x38, 0x8a, 0x97, 0x98, 0x98, 0xd8, 0x14,
	0x61, 0x67, 0x40, 0x86, 0x3d, 0xb1, 0x9b, 0xd9, 0x39, 0x78, 0x96, 0x81, 0x1e, 0x81, 0xf7, 0xfe,
	0xea, 0x86, 0x07, 0x2d, 0x0a, 0xe0, 0x4f, 0xa4, 0x9c, 0x44, 0xef, 0x02, 0x42, 0xfb, 0xd0, 0x15,
	0x3c, 0xe2, 0xd3, 0x1b, 0xfe, 0xf9, 0xed, 0x54, 0x06, 0x6d, 0x76, 0x06, 0xdd, 0xcb, 0x34, 0x4e,
	0x04, 0x7e, 0xd9, 0x60, 0x6e, 0x1a, 0xcc, 0xe4, 0x80, 0xf9, 0x3b, 0xf4, 0xdc, 0x6a, 0xae, 0xd3,
	0x24, 0x47, 0x7a, 0xd6, 0xb0, 0xf0, 0xd8, 0x5a, 0xa8, 0xe3, 0x75, 0x23, 0x2f, 0xe0, 0x58, 0x6d,
	0xcc, 0x2a, 0xcd, 0xe2, 0xaf, 0xca, 0x9a, 0x2c, 0xfd, 0xf4, 0x44, 0xf3, 0x90, 0x9d, 0x56, 0xd2,
	0xad, 0xe0, 0x28, 0xe2, 0x33, 0xe9, 0xc4, 0x0b, 0x7e, 0xc9, 0x23, 0x19, 0x10, 0xf6, 0x93, 0x80,
	0x3f, 0xbb, 0x53, 0x05, 0x66, 0xff, 0xd2, 0x49, 0x7b, 0x40, 0xb6, 0x55, 0x60, 0x64, 0x6b, 0x27,
	0x17, 0x52, 0x47, 0x90, 0xc2, 0x26, 0xba, 0x42, 0x75, 0x67, 0x56, 0xa1, 0xe7, 0x12, 0x75, 0x13,
	0x3d, 0x05, 0xc0, 0xad, 0xc6, 0x2c, 0xc6, 0x64, 0x81, 0xe1, 0xbd, 0x12, 0xab, 0x9d, 0xec, 0x9e,
	0xcb, 0xdf, 0x3f, 0x97, 0x53, 0x52, 0x73, 0xc9, 0x9e, 0xd5, 0xf5, 0xcb, 0x69, 0x19, 0xfe, 0x31,
	0xdc, 0xbf, 0x9e, 0xf1, 0x48, 0x4e, 0xe4, 0x95, 0x08, 0x08, 0xfb, 0x04, 0x0f, 0xaf, 0x8d, 0x32,
	0x9b, 0xfc, 0x83, 0x5e, 0x2a, 0x83, 0xbf, 0x63, 0x67, 0xe0, 0xeb, 0x92, 0xae, 0x34, 0xd3, 0x1d,
	0xc3, 0xfe, 0x02, 0x51, 0x21, 0x76, 0x47, 0x2d, 0x76, 0xe1, 0x55, 0x3b, 0xae, 0x33, 0xa2, 0x42,
	0xd8, 0x2b, 0x78, 0xd4, 0xa4, 0xaf, 0x9e, 0xea, 0x3f, 0xf8, 0xc7, 0xdf, 0xc0, 0x7b, 0xa3, 0xd6,
	0x48, 0x39, 0x40, 0x94, 0x26, 0x09, 0xba, 0x9e, 0x3e, 0xb5, 0x9b, 0x7f, 0x91, 0x7c, 0x12, 0xfe,
	0x09, 0xb8, 0xcb, 0x58, 0x6b, 0x48, 0x2e, 0x08, 0x3d, 0x07, 0xcf, 0xb6, 0x81, 0xf6, 0xf7, 0xbd,
	0x70, 0x1f, 0x06, 0x87, 0x45, 0x61, 0xad, 0x0b, 0xf2, 0xda, 0xfb, 0xd8, 0xd6, 0xf3, 0xb9, 0x5f,
	0xfe, 0x2b, 0x2f, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff, 0xc5, 0x44, 0x27, 0x97, 0x39, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GameClient is the client API for Game service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GameClient interface {
	Connection(ctx context.Context, opts ...grpc.CallOption) (Game_ConnectionClient, error)
	Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (Game_JoinClient, error)
}

type gameClient struct {
	cc *grpc.ClientConn
}

func NewGameClient(cc *grpc.ClientConn) GameClient {
	return &gameClient{cc}
}

func (c *gameClient) Connection(ctx context.Context, opts ...grpc.CallOption) (Game_ConnectionClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Game_serviceDesc.Streams[0], "/pb.Game/Connection", opts...)
	if err != nil {
		return nil, err
	}
	x := &gameConnectionClient{stream}
	return x, nil
}

type Game_ConnectionClient interface {
	Send(*StatusUpdateRequest) error
	Recv() (*StatusUpdateResponse, error)
	grpc.ClientStream
}

type gameConnectionClient struct {
	grpc.ClientStream
}

func (x *gameConnectionClient) Send(m *StatusUpdateRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gameConnectionClient) Recv() (*StatusUpdateResponse, error) {
	m := new(StatusUpdateResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gameClient) Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (Game_JoinClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Game_serviceDesc.Streams[1], "/pb.Game/Join", opts...)
	if err != nil {
		return nil, err
	}
	x := &gameJoinClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Game_JoinClient interface {
	Recv() (*JoinResponse, error)
	grpc.ClientStream
}

type gameJoinClient struct {
	grpc.ClientStream
}

func (x *gameJoinClient) Recv() (*JoinResponse, error) {
	m := new(JoinResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GameServer is the server API for Game service.
type GameServer interface {
	Connection(Game_ConnectionServer) error
	Join(*JoinRequest, Game_JoinServer) error
}

// UnimplementedGameServer can be embedded to have forward compatible implementations.
type UnimplementedGameServer struct {
}

func (*UnimplementedGameServer) Connection(srv Game_ConnectionServer) error {
	return status.Errorf(codes.Unimplemented, "method Connection not implemented")
}
func (*UnimplementedGameServer) Join(req *JoinRequest, srv Game_JoinServer) error {
	return status.Errorf(codes.Unimplemented, "method Join not implemented")
}

func RegisterGameServer(s *grpc.Server, srv GameServer) {
	s.RegisterService(&_Game_serviceDesc, srv)
}

func _Game_Connection_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GameServer).Connection(&gameConnectionServer{stream})
}

type Game_ConnectionServer interface {
	Send(*StatusUpdateResponse) error
	Recv() (*StatusUpdateRequest, error)
	grpc.ServerStream
}

type gameConnectionServer struct {
	grpc.ServerStream
}

func (x *gameConnectionServer) Send(m *StatusUpdateResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gameConnectionServer) Recv() (*StatusUpdateRequest, error) {
	m := new(StatusUpdateRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Game_Join_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(JoinRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GameServer).Join(m, &gameJoinServer{stream})
}

type Game_JoinServer interface {
	Send(*JoinResponse) error
	grpc.ServerStream
}

type gameJoinServer struct {
	grpc.ServerStream
}

func (x *gameJoinServer) Send(m *JoinResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Game_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Game",
	HandlerType: (*GameServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connection",
			Handler:       _Game_Connection_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Join",
			Handler:       _Game_Join_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "game.proto",
}
